feat: order address tokens by latest tx timestamp
HathorNetwork/hathor-explorer-service pull request #200
Opened 2022-08-25 18:34 UTC by r4mmer

### Acceptance Criteria
- Order address tokens by latest tx `timestamp` instead of `updated_at` column

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2022-08-26 15:22 UTC, andreabadesso approved these changes

2022-08-26 15:28 UTC, andreabadesso requested changes

2022-08-26 15:28 UTC, andreabadesso commented on gateways/clients/wallet_service_db_client.py
> +ORDER BY address_tokens.timestamp DESC
```suggestion
    SELECT token.id AS token_id,
           token.name AS name,
           token.symbol AS symbol
      FROM token
INNER JOIN (
               SELECT token_id,
                      MAX(timestamp) AS timestamp
                 FROM address_tx_history
                WHERE address = :address
                  AND token_id != '00'
             GROUP BY token_id
            ) address_tokens
        ON token.id = address_tokens.token_id
  ORDER BY address_tokens.timestamp DESC
```

2022-08-26 20:57 UTC, andreabadesso approved these changes

2022-08-29 15:06 UTC, pedroferreira1 approved these changes

2022-08-29 17:35 UTC, merged