feat: improve network statistics api
HathorNetwork/hathor-explorer-service pull request #273
Opened 2023-10-10 13:53 UTC by alexruzenhack

This was motivated by a request from a developer of Proteina.

### Acceptance Criteria
- feat: add total_blocks to network_statistics endpoint
- feat: add nano contract to total_transactions aggregation

### Security Checklist
- [ ] Make sure you do not include new dependencies in the project unless strictly necessary and do not include dev-dependencies as production ones. More dependencies increase the possibility of one of them being hijacked and affecting us.

2023-10-10 14:44 UTC, luislhl approved these changes

2023-10-10 15:39 UTC, r4mmer requested changes

2023-10-11 22:52 UTC, alexruzenhack commented on gateways/network_statistics_api_gateway.py
> +                            "source": f"doc['version'].value == {TxVersion.REGULAR_TRANSACTION} || doc['version'].value == {TxVersion.TOKEN_CREATION_TRANSACTION} || doc['version'].value == {TxVersion
I updated the python and hathorlib dependencies, see:
- 9a997d4e7cd8ba79eda73b0d4b095198bd42186b
- 21ed04d7661ba6c0120c33402c6e47973c1edb5d
- a126e8b04a09cc547407da6cd27ccb84adca7124

2023-10-23 16:55 UTC, alexruzenhack commented on usecases/network_statistics_api.py
> +                "ExplorerService failed to fetch transaction statistics from ElasticSearch"
I removed it because the other `logger.error` usage don't use it as well. I'm afraid to break something.

2023-10-23 16:55 UTC, merged